services:
  node:
    image: node:22
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: ./infra/entrypoint.sh
    depends_on:
      - mysql
  mysql:
    image: mysql:8.4-oraclelinux8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: