services:
  node:
    image: node:22
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: ./infra/entrypoint.sh
    expose:
      - "3000"
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: ghcr.io/ame180/nginx-node:latest
    depends_on:
      - node
    ports:
      - "80:80"

  mysql:
    image: ghcr.io/ame180/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: