services:
  node:
    image: ghcr.io/ame180/amebot-node:latest
    build:
      context: .
      dockerfile: infra/Dockerfile-prod
    volumes:
      - ./db.sqlite:/app/db.sqlite
    working_dir: /app
    entrypoint: infra/entrypoint-prod.sh
    depends_on:
      - mysql
  mysql:
    image: mysql:8.4-oraclelinux8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: