FROM node:22 as build
WORKDIR /app

COPY . .
RUN yarn install
RUN yarn build

FROM node:22 as prod
WORKDIR /app

COPY . .
COPY --from=build /app/dist ./dist

RUN yarn install --prod
RUN chmod +x infra/entrypoint-prod.sh