FROM node:22 as build
WORKDIR /app

COPY tsconfig.json package.json yarn.lock ./
COPY config.dist.json ./config.json
COPY src ./src
RUN yarn install && yarn build

FROM node:22 as prod
WORKDIR /app

COPY infra/entrypoint-prod.sh entrypoint.sh
RUN chmod +x entrypoint.sh

COPY .sequelizerc package.json yarn.lock ./
RUN yarn install --prod
COPY --from=build /app/dist ./dist
