name: ESLint

on:
  - push
  - pull_request

env:
  NODE_VERSION: '22.x'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy .env and config.json
        run: cp .env.dist .env && cp config.dist.json config.json
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: yarn install
      - name: Run ESLint
        run: yarn eslint